name: 'Run General filesystem tests'
description: 'Run basic filesystem checks'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  check-gitignore:
    description: 'Checks the code for files that should be ignored via .gitignore'
    required: false
    default: 'true'
  check-git-conflict:
    description: 'Checks the code for git conflicts'
    required: false
    default: 'true'
  conflict-files:
    description: 'Additional files to check/ignore for git conflicts'
    required: false
    default: "':!buddy.yml' ':!.buddy/*'"

runs:
  using: 'composite'
  steps:
      - name: Check for gitignored files
        if: inputs.check-gitignore != 'false'
        shell: bash
        run: |
          IGNORED_FILES=$(git ls-files -ci --exclude-standard)
          if [[ ! -z "$IGNORED_FILES" ]]; then
            echo "Gitignored files found:" >&2
            echo "$IGNORED_FILES" >&2
            exit 1
          fi

      - name: Check for git conflicts
        if: inputs.check-git-conflict != 'false'
        shell: bash
        run: |
          CONFLICTS=$(git grep -l -E "<<<<<<< |>>>>>>> " -- './*' ${{ inputs.conflict-files }} || true)
          if [[ ! -z "$CONFLICTS" ]]; then
            echo "Git conflicts found in:" >&2
            echo "$CONFLICTS" >&2
            echo "Review these files and resolve conflicts before committing." >&2
            exit 1
          fi
